name: Code Quality
on: [push]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: Python Poetry
        uses: abatilo/actions-poetry@v2.1.3
      - run: poetry install
      - run: poetry run mypy *.py
